### ISSUE TITLE
It work well if few image,but not work in lots of image in a page.

### ISSUE THREAD

**Issue by jksbill** [mycure-inc/vue-html2canvas#10]
i want to download html page as png with vue html2canvas, if lots of image in the page, download failed and giving network Error in chrome

**Comment by jksbill** [comment]
yes, html2canvas work well, i think something wrong with my download code,thinks for you help ^_^.

**Comment by jofftiquez** [comment]
Thanks @jksbill please let me know if I could help you with something.
