### ISSUE TITLE
Syntax Error: SyntaxError: .../src/views/Page.vue: await is a reserved word

### ISSUE THREAD

**Issue by zacsneds** [mycure-inc/vue-html2canvas#2]
Hey mate.

I am having trouble getting past the error on this line from your example.
`'this.output = await this.$html2canvas(el, options)'`

The error is
`Syntax Error: SyntaxError: .../src/views/Page.vue: await is a reserved word`

Any ideas on how I can fix this?

Thanks in advance!
Zac

**Comment by jofftiquez** [comment]
Hey Zac, thanks for using this plugin.

`this.$html2canvas()` is a promise so if you're not using async await you could do this: 

```
this.$html2canvas(el, options)
    .then(output => {
        // output here
    })
    .catch(error => console.error(error))
```

Let me know it this works.

Cheers!

**Comment by jofftiquez** [comment]
Closing this for now.
