### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Leolik** [mycure-inc/vue-html2canvas#3]
I get this error in console after adding
```
import Vue from 'vue';
import VueHtml2Canvas from 'vue-html2canvas';

Vue.use(VueHtml2Canvas);
```
into main.js

**Comment by Leolik** [comment]
fixed
need add `babel-polyfill` to project

**Comment by jofftiquez** [comment]
Aaaah the magical `babel-polyfill` savior of all. Thanks for using this repo @Leolik

**Comment by jofftiquez** [comment]
@vanoneang I am not aware of any other way yet, but as long as we are using `async` `await`, we really need `babel-polyfill`

**Comment by ateeqrgondal** [comment]
How did you add babel-polyfill in vue cli3 project?  I could not make it work.

**Comment by ateeqrgondal** [comment]
@jofftiquez  can you please help.

**Comment by jofftiquez** [comment]
@ateeqrgondal async await is already built-in in vue cli 3.

**Comment by ateeqrgondal** [comment]
Thank you @jofftiquez . Can you let me know why I am getting this error then "Uncaught ReferenceError: regeneratorRuntime is not defined" ? When I use vue-html2canvas as Vue.use(html2Canvas), I am getting this error.

**Comment by jofftiquez** [comment]
@ateeqrgondal I am not getting that error in vue cli 3. :/

**Comment by ejoo** [comment]
https://www.npmjs.com/package/regenerator-runtime

This also helped me.

**Comment by jonyedu** [comment]
> https://www.npmjs.com/package/regenerator-runtime
> 
> Esto también me ayudó.

Muchas gracias, me funciono.
